name: DEV - Workflow
on:
  pull_request:
    types: 
      - opened
jobs:
  build-project:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18.12.0'
      - run: npm run build:dev
      - run: node --version
        
  